serverAddress: localhost:9092
topics:
- name: registry.incident.address.save
  message: |-
    [
       {
          "queryId": "166000233-f229-100b-2211-3300173721124",
          "address": {
             "country": "Россия",
             "subject": "Алтайский край",
             "region": "Алейский район",
             "locality": "Алейский поселок",
             "street": "Геройская улица",
             "house": "1",
             "flat": "3"
          },
          "matched": {
             "country": "1",
             "subject": "e3afe7fb-18dc-45de-8349-13d6ff1c1fc2",
             "region": "135637827259064320000366007",
             "locality": "b8cf869a-2d4f-49bc-a373-a2ce871cd209",
             "street": "138529545693557760000339871",
             "house": "138529545693557760000347531"
          },
          "lastFoundNodeId": "138529545693557760000347531",
          "incidentless": false,
          "stdList": [
             "00C000"
          ],
          "targetSchema": "ADDRESS",
          "searchMethod": "TREE",
          "incomeStd": "00C000",
          "loadingId": "2111a845-f229-428b-b1c5-512427c89923",
          "loadingFileName": "5-Событие смена ФИО.txt",
          "id": "79918c23-94e5-43c3-8170-8c1e1d3308e5",
          "std": "00C000",
          "status": "CREATED"
       }
    ]
  headers: ['sdf: sdf']
- name: address.registry.index.sync
  message: |-
    [
       {
          "queryId": "166000233-f229-100b-2211-3300173721124",
          "address": {
             "country": "Россия",
             "subject": "Алтайский край",
             "region": "Алейский район",
             "locality": "Алейский поселок",
             "street": "Геройская улица",
             "house": "1",
             "flat": "3"
          },
          "matched": {
             "country": "1",
             "subject": "e3afe7fb-18dc-45de-8349-13d6ff1c1fc2",
             "region": "135637827259064320000366007",
             "locality": "b8cf869a-2d4f-49bc-a373-a2ce871cd209",
             "street": "138529545693557760000339871",
             "house": "138529545693557760000347531"
          },
          "lastFoundNodeId": "138529545693557760000347531",
          "incidentless": false,
          "stdList": [
             "00C000"
          ],
          "targetSchema": "ADDRESS",
          "searchMethod": "TREE",
          "incomeStd": "00C000",
          "loadingId": "2111a845-f229-428b-b1c5-512427c89923",
          "loadingFileName": "5-Событие смена ФИО.txt",
          "id": "79918c23-94e5-43c3-8170-8c1e1d3308e5",
          "std": "00C000",
          "status": "CREATED"
       }
    ]
  headers: null
- name: registry.address.create-by-search.request
  message: |-
    [
       {
          "stdList": [
             "30T002",
             "30S000",
             "00C000"
          ],
          "queryId": "8dae4521-b4c8-435c-a644-f0000011fee3",
          "PARENT": [
             "141267329645411840000388476",
             "141267329645411840000339571",
             "135637827259064320000362989",
             "135637827259064320000362906",
             "1"
          ],
          "IADDRESS_LEVELID": "11",
          "VCADDRESS_NAME": "2"
       }
    ]
  headers: null
- name: address.searchnode.addressstruct.search
  message: " \n[\n   {\n      \"queryId\": \"124053540-f270-100a-2231-33001721124\"\
    ,\n      \"incomeStd\": \"00C000\",\n      \"address\": {\n         \"country\"\
    : \"Россия\",\n         \"subject\": \"Тульская область\",\n         \"locality\"\
    : \"Донской\",\n         \"street\": \"Грького\"\n      },\n      \"loadingId\"\
    : \"2111a845-f229-728b-b1c5-512427c00923\",\n      \"loadingFileName\": \"5-Со\
    бытие смена ФИО.txt\",\n      \"targetSchema\": \"ADDRESS\"\n   }\n]"
  headers: null
- name: address.searchnode.address.create-root
  message: |-
    {
       "parentsIds": [
          [
             "1"
          ]
       ],
       "id": "68725e6f-61ef-43da-b627-6622e262d2ab",
       "modified": 1689938957,
       "IADDRESSID": "0e7b4522-a41b-4b9a-a920-57842002d7b7",
       "VCADDRESS_NAME": "Аляска",
       "parents": [
          {
             "id": "1",
             "empty": false,
             "IADDRESSID": "1",
             "VCADDRESS_NAME": "Россия",
             "IADDRESS_LEVELID": "1",
             "ISERVERID": "13563782725906432",
             "STD": "00C000",
             "IIS_ATOM": false,
             "IIS_UNCHECKED": false,
             "IPR_INDIRECT_DEPEND": false
          }
       ],
       "IADDRESS_LEVELID": "2",
       "IIS_ATOM": false,
       "IIS_UNCHECKED": false,
       "fullNameList": "[{\"name\":\"Россия, Аляска\",\"parents\":[\"1\",\"68725e6f-61ef-43da-b627-6622e262d2ab\"]}]",
       "fullNameHistory": "[{\"id\":\"5a513b80-76ee-486c-813c-aaa6422f15e6\",\"changed\":1689844883,\"name\":\"Канзас2\"},{\"id\":\"0e7b4522-a41b-4b9a-a920-57842002d7b7\",\"changed\":1687791945,\"name\":\"(тест)КРАСНОЯРСКИЙ КРАЙ\"}]",
       "isRetro": false
    }
  headers: null
- name: gas-address.searchnode.address.create-root
  message: |-
    {
       "parentsIds": [
          [
             "1"
          ]
       ],
       "id": "68725e6f-61ef-43da-b627-6622e262d2ab",
       "modified": 1689938957,
       "IADDRESSID": "0e7b4522-a41b-4b9a-a920-57842002d7b7",
       "VCADDRESS_NAME": "Аляска",
       "parents": [
          {
             "id": "1",
             "empty": false,
             "IADDRESSID": "1",
             "VCADDRESS_NAME": "Россия",
             "IADDRESS_LEVELID": "1",
             "ISERVERID": "13563782725906432",
             "STD": "00C000",
             "IIS_ATOM": false,
             "IIS_UNCHECKED": false,
             "IPR_INDIRECT_DEPEND": false
          }
       ],
       "IADDRESS_LEVELID": "2",
       "IIS_ATOM": false,
       "IIS_UNCHECKED": false,
       "fullNameList": "[{\"name\":\"Россия, Аляска\",\"parents\":[\"1\",\"68725e6f-61ef-43da-b627-6622e262d2ab\"]}]",
       "fullNameHistory": "[{\"id\":\"5a513b80-76ee-486c-813c-aaa6422f15e6\",\"changed\":1689844883,\"name\":\"Канзас2\"},{\"id\":\"0e7b4522-a41b-4b9a-a920-57842002d7b7\",\"changed\":1687791945,\"name\":\"(тест)КРАСНОЯРСКИЙ КРАЙ\"}]",
       "isRetro": false
    }
  headers: null
- {name: address.registry.search.node.archived, message: archived, headers: null}
- name: registry.nsi.document-request
  message: " \n{\n   \"schema\": \"NSI13\",\n   \"generateExpands\": false,\n   \"\
    docsPerBatch\": 999\n}"
  headers: null
- name: gas-address.searchnode.addressstruct.search
  message: " \n[\n   {\n      \"queryId\": \"124053540-f270-100a-2231-33001721124\"\
    ,\n      \"incomeStd\": \"00C000\",\n      \"address\": {\n         \"country\"\
    : \"Россия\",\n         \"subject\": \"Тульская область\",\n         \"locality\"\
    : \"Донской\",\n         \"street\": \"Грького\"\n      },\n      \"loadingId\"\
    : \"2111a845-f229-728b-b1c5-512427c00923\",\n      \"loadingFileName\": \"5-Со\
    бытие смена ФИО.txt\",\n      \"targetSchema\": \"ADDRESS\"\n   }\n]"
  headers: null
